name: AWS Policy Reader

on:
  workflow_dispatch:
    inputs:
      role-name:
        description: 'IAM role name to read'
        required: true
        default: 'terragrunt-execution-role'
      account-id:
        description: 'AWS Account ID'
        required: true
        default: '567749996660'
      environment-name:
        description: 'Environment name'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:
  read-aws-policies:
    runs-on: ubuntu-latest
    name: Read AWS Execution Policies
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Read AWS Role Policies
      id: read-policies
      uses: GergoNagy94/devops-tools/aws-execution-policy-reader@main
      with:
        role-name: ${{ inputs.role-name }}
        account-id: ${{ inputs.account-id }}
        environment-name: ${{ inputs.environment-name }}
    
    - name: Upload policies artifact
      if: steps.read-policies.outputs.has-role == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: aws-policies-${{ inputs.environment-name }}-${{ github.run_number }}
        path: ${{ steps.read-policies.outputs.policies-file }}
    
    - name: Display policies summary
      if: steps.read-policies.outputs.has-role == 'true'
      shell: bash
      run: |
        echo "## AWS Role Policies Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Role Name**: ${{ inputs.role-name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Account ID**: ${{ inputs.account-id }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Environment**: ${{ inputs.environment-name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Policies File**: ${{ steps.read-policies.outputs.policies-file }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [[ -f "${{ steps.read-policies.outputs.policies-file }}" ]]; then
          managed_count=$(jq '.policies.managed | length' "${{ steps.read-policies.outputs.policies-file }}")
          inline_statements=$(jq '.policies.inline.Statement | length' "${{ steps.read-policies.outputs.policies-file }}")
          echo "- **Managed Policies**: $managed_count" >> $GITHUB_STEP_SUMMARY
          echo "- **Inline Policy Statements**: $inline_statements" >> $GITHUB_STEP_SUMMARY
        fi