name: Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Scan for secrets
      id: secrets
      uses: GergoNagy94/devops-tools/secret-leaks@main
      with:
        path: '.'
        fail-on-secrets: 'true'
    
    - name: Upload report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: secrets-report
        path: ${{ steps.secrets.outputs.report-file }}