name: Module Version Checker

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Directory to scan'
        required: true
        default: 'infrastructure/live/dev'
        options:
          - infrastructure/live/dev
          - infrastructure/live/prod
        type: choice
      outdated-only:
        description: 'Show only outdated modules'
        required: false
        default: false
        type: boolean

jobs:
  test-module-checker:
    runs-on: ubuntu-latest
    name: Test Module Version Checker
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Run Terraform Module Version Checker
      id: run-checker
      uses: GergoNagy94/devops-tools/terraform-version-checker@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        environment: ${{ inputs.environment }}
        outdated-only: ${{ inputs.outdated-only }}
    
    - name: Upload module version report
      uses: actions/upload-artifact@v4
      with:
        name: terraform-versions-${{ github.run_number }}
        path: ${{ steps.run-checker.outputs.report-file }}