name: Example Terraform Version Check

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to check'
        required: true
        default: 'units'
      outdated_only:
        description: 'Show only outdated modules'
        type: boolean
        default: false

jobs:
  check-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check Terraform versions
        id: check
        uses: GergoNagy94/devops-tools/terraform-version-checker@v1.0.0
        with:
          environment: ${{ github.event.inputs.environment }}
          outdated-only: ${{ github.event.inputs.outdated_only }}
      
      - name: Show results
        run: |
          echo "Report: ${{ steps.check.outputs.report-file }}"
          echo "Outdated: ${{ steps.check.outputs.outdated-count }}"
          
          # Report is stored in the environment directory specified in the input
          # For example: units/terraform-versions-units.yml or units/terraform-versions-units-outdated.yml
          if [ -f "${{ steps.check.outputs.report-file }}" ]; then
            echo ""
            echo "Report preview:"
            head -20 "${{ steps.check.outputs.report-file }}"
          fi

      - name: Upload report
        if: steps.check.outputs.report-file != ''
        uses: actions/upload-artifact@v4
        with:
          name: terraform-version-report
          path: ${{ steps.check.outputs.report-file }}