name: 'Secret Scanner'
description: 'Scan repository for accidentally committed secrets'

inputs:
  path:
    description: 'Path to scan'
    required: false
    default: '.'
  fail-on-secrets:
    description: 'Fail if secrets are found'
    required: false
    default: 'true'

outputs:
  secrets-found:
    description: 'Number of secrets found'
    value: ${{ steps.scan.outputs.secrets-found }}
  report-file:
    description: 'Path to report file'
    value: ${{ steps.scan.outputs.report-file }}

runs:
  using: 'composite'
  steps:
    - name: Install Gitleaks
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/master/scripts/install.sh | sh -s -- -d /tmp
        echo "/tmp" >> $GITHUB_PATH

    - name: Scan for secrets
      id: scan
      shell: bash
      run: |
        #!/bin/bash
        set -e
        
        SCAN_PATH="${{ inputs.path }}"
        FAIL_ON_SECRETS="${{ inputs.fail-on-secrets }}"
        REPORT_FILE="secrets-report.json"
        
        echo "Scanning for secrets in: $SCAN_PATH"
        
        # Run gitleaks scan
        if gitleaks detect --source="$SCAN_PATH" --report-format=json --report-path="$REPORT_FILE" --exit-code=0 --no-git; then
          SECRETS_COUNT=0
        else
          SECRETS_COUNT=$(jq length "$REPORT_FILE" 2>/dev/null || echo "0")
        fi
        
        echo "secrets-found=$SECRETS_COUNT" >> $GITHUB_OUTPUT
        echo "report-file=$REPORT_FILE" >> $GITHUB_OUTPUT
        
        if [[ $SECRETS_COUNT -gt 0 ]]; then
          echo "Found $SECRETS_COUNT potential secrets!"
          
          # Show summary
          if command -v jq &> /dev/null && [[ -f "$REPORT_FILE" ]]; then
            echo "Summary:"
            jq -r '.[] | "  - \(.File):\(.StartLine) (\(.RuleID))"' "$REPORT_FILE" | head -10
            [[ $SECRETS_COUNT -gt 10 ]] && echo "  ... and $((SECRETS_COUNT - 10)) more"
          fi
          
          if [[ "$FAIL_ON_SECRETS" == "true" ]]; then
            echo "Failing build due to secrets found"
            exit 1
          fi
        else
          echo "No secrets found!"
        fi